name: treat 😺

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write  # Allows posting comments on PRs
  issues: write

jobs:
  aCatForCreatingThePullRequest:
    name: 'A treat for your effort!'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: parthiv13/PRaiseMeSenpai@0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
